name: homecare_app
description: 'Aplikasi yang diperuntukan untuk mencari dan menawarkan berbagai jasa.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  url_launcher: ^6.0.6
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dotted_border: ^2.1.0
  fetchly: ^0.0.2
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  go_router: ^10.1.2
  hooks_riverpod: ^2.4.0
  image_picker: ^1.0.6
  lazyui: ^1.0.12
  riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  dart_jsonwebtoken: ^2.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoNoLabel.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
